version: '3'
services:
  frontend:
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'

  nginx:
    restart: unless-stopped
    image: nginx
    volumes:
      - ./nginx/:/etc/nginx/
    depends_on:
      - backend
      - frontend
    ports:
      - '80:80'

  backend:
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'

  foodDB:
    image: postgres
    restart: unless-stopped
    container_name: foodDB
    env_file:
      - .env
    ports:
      - '5436:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    env_file:
      - .env
    command: start-dev
    ports:
      - '8080:8080'
    depends_on:
      - foodDB
