version: '4'
services:
  frontend:
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'

  backend:
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'

  foodDB:
    image: postgres
    restart: unless-stopped
    container_name: foodDB
    env_file:
      - .env
    ports:
      - '5436:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  keycloak:
    platform: linux/amd64
    build:
      context: ./keycloak
      dockerfile: ./Dockerfile
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - '8080:8080'
    volumes:
      - ./keycloak_volumes:/opt/keycloak/data/import
    depends_on:
      - foodDB
